Add database
AleksandrKGit/java-filmorate pull request #3
Opened 2022-12-01 02:06 UTC by AleksandrKGit

2022-12-02 05:55 UTC, ErkinKasymaliev requested changes
Привет, работа хорошая, но есть где доработать

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBFilmStorage.java
> +@Primary
неплохо

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +        checkId(user.getId());
Это лишнее, если нет такого id, update ошибки не кинет, но и не обновит ничего. А здесь вы лишний запрос в бд делаете, а это нехорошо. Вроде jdbcTemplate.update() вернет null, тут просто добавьте сообщение что такого юзера нет.

Также этот метод у вас много где вызывается этот метод checkId(), что опять же вызывает лишние запросы к БД, так не пойдет. Подумайте как обойтись без этого метода. По идее он вам не нужен нигде.

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +        User user = get(id);
а если такого юзера нет?

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "SELECT ID FROM (" +
давайте перепишите через join

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "    SELECT FROM_USER_ID AS ID FROM FRIENDSHIP_REQUESTS WHERE TO_USER_ID = ? " +
здесь тоже через join перепишите

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "WHERE U.ID IN (SELECT FROM_USER_ID FROM FRIENDSHIP_REQUESTS WHERE TO_USER_ID = ?" +
здесь тоже через join перепишите

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "WHERE U.ID IN (SELECT FROM_USER_ID FROM FRIENDSHIP_REQUESTS WHERE TO_USER_ID = ? AND STATUS " +
здесь тоже через join перепишите

2022-12-02 05:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBFilmStorage.java
> +    private void checkId(Integer id) {
оставил коммент в DBUserStorage по поводу аналогичного метода

2022-12-02 08:18 UTC, AleksandrKGit commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +        User user = get(id);
То  get(id) выбросит исключение

2022-12-02 08:18 UTC, AleksandrKGit commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "SELECT ID FROM (" +
ОК

2022-12-02 08:18 UTC, AleksandrKGit commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "    SELECT FROM_USER_ID AS ID FROM FRIENDSHIP_REQUESTS WHERE TO_USER_ID = ? " +
ОК

2022-12-02 08:19 UTC, AleksandrKGit commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +        checkId(user.getId());
ОК

2022-12-02 08:25 UTC, AleksandrKGit commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "WHERE U.ID IN (SELECT FROM_USER_ID FROM FRIENDSHIP_REQUESTS WHERE TO_USER_ID = ?" +
OK

2022-12-02 08:25 UTC, AleksandrKGit commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DBUserStorage.java
> +                        "WHERE U.ID IN (SELECT FROM_USER_ID FROM FRIENDSHIP_REQUESTS WHERE TO_USER_ID = ? AND STATUS " +
OK

2022-12-04 07:39 UTC, ErkinKasymaliev approved these changes
привет, все отлично, работа принята

2022-12-19 08:25 UTC, merged